version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Chicago
  open-pull-requests-limit: 10
  reviewers:
  - jason-edstrom
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Chicago
  open-pull-requests-limit: 10
  reviewers:
  - jason-edstrom
  
